global using Application = System.Windows.Application;
global using Button = System.Windows.Controls.Button;
global using CheckBox = System.Windows.Controls.CheckBox;
global using ComboBox = System.Windows.Controls.ComboBox;
global using ListBox = System.Windows.Controls.ListBox;
global using TabControl = System.Windows.Controls.TabControl;
global using TextBox = System.Windows.Controls.TextBox;
global using Orientation = System.Windows.Controls.Orientation;
global using Brushes = System.Windows.Media.Brushes;
global using Color = System.Windows.Media.Color;
global using SystemColors = System.Windows.SystemColors;
global using System.IO;
