param([string]$OutputDirectory = $PSScriptRoot)
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
function New-RoundedPath([float]$x,[float]$y,[float]$w,[float]$h,[float]$r){$p=[Drawing.Drawing2D.GraphicsPath]::new();$d=$r*2;$p.AddArc($x,$y,$d,$d,180,90);$p.AddArc($x+$w-$d,$y,$d,$d,270,90);$p.AddArc($x+$w-$d,$y+$h-$d,$d,$d,0,90);$p.AddArc($x,$y+$h-$d,$d,$d,90,90);$p.CloseFigure();$p}
function New-LogoPng([int]$size){
  $b=[Drawing.Bitmap]::new($size,$size,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$g=[Drawing.Graphics]::FromImage($b);$g.SmoothingMode='AntiAlias';$g.PixelOffsetMode='HighQuality';$g.ScaleTransform($size/256.0,$size/256.0)
  $tile=New-RoundedPath 8 8 240 240 52;$tb=[Drawing.Drawing2D.LinearGradientBrush]::new([Drawing.PointF]::new(8,8),[Drawing.PointF]::new(248,248),[Drawing.ColorTranslator]::FromHtml('#182338'),[Drawing.ColorTranslator]::FromHtml('#0B1020'));$g.FillPath($tb,$tile)
  $screen=New-RoundedPath 38 39 180 126 20;$sb=[Drawing.Drawing2D.LinearGradientBrush]::new([Drawing.PointF]::new(38,39),[Drawing.PointF]::new(218,165),[Drawing.ColorTranslator]::FromHtml('#0B3347'),[Drawing.ColorTranslator]::FromHtml('#17143D'));$cp=[Drawing.Pen]::new([Drawing.ColorTranslator]::FromHtml('#45D8EF'),13);$g.FillPath($sb,$screen);$g.DrawPath($cp,$screen)
  $sp=[Drawing.Pen]::new([Drawing.ColorTranslator]::FromHtml('#45D8EF'),12);$sp.StartCap=$sp.EndCap='Round';$g.DrawLine($sp,110,165,110,190);$g.DrawLine($sp,146,165,146,190);$g.DrawLine($sp,86,196,170,196)
  [Drawing.PointF[]]$padPoints=@([Drawing.PointF]::new(63,142),[Drawing.PointF]::new(85,120),[Drawing.PointF]::new(104,114),[Drawing.PointF]::new(152,114),[Drawing.PointF]::new(171,120),[Drawing.PointF]::new(193,142),[Drawing.PointF]::new(206,181),[Drawing.PointF]::new(190,205),[Drawing.PointF]::new(161,190),[Drawing.PointF]::new(95,190),[Drawing.PointF]::new(66,205),[Drawing.PointF]::new(50,181));$pad=[Drawing.Drawing2D.GraphicsPath]::new();$pad.AddClosedCurve($padPoints,0.35)
  $pb=[Drawing.Drawing2D.LinearGradientBrush]::new([Drawing.PointF]::new(50,114),[Drawing.PointF]::new(206,206),[Drawing.ColorTranslator]::FromHtml('#8B5CF6'),[Drawing.ColorTranslator]::FromHtml('#5B35CF'));$pp=[Drawing.Pen]::new([Drawing.ColorTranslator]::FromHtml('#C4B5FD'),7);$g.FillPath($pb,$pad);$g.DrawPath($pp,$pad)
  $wp=[Drawing.Pen]::new([Drawing.ColorTranslator]::FromHtml('#ECFEFF'),9);$wp.StartCap=$wp.EndCap='Round';$g.DrawLine($wp,91,145,91,173);$g.DrawLine($wp,77,159,105,159);$cyan=[Drawing.SolidBrush]::new([Drawing.ColorTranslator]::FromHtml('#45D8EF'));$white=[Drawing.SolidBrush]::new([Drawing.ColorTranslator]::FromHtml('#ECFEFF'));$g.FillEllipse($cyan,158,144,14,14);$g.FillEllipse($white,174,159,14,14);$g.FillEllipse($cyan,123,168,12,12)
  $m=[IO.MemoryStream]::new();$b.Save($m,[Drawing.Imaging.ImageFormat]::Png);$bytes=$m.ToArray();$m.Dispose();$g.Dispose();$b.Dispose();@($tile,$tb,$screen,$sb,$cp,$sp,$pad,$pb,$pp,$wp,$cyan,$white)|ForEach-Object{$_.Dispose()};,$bytes
}
[IO.Directory]::CreateDirectory($OutputDirectory)|Out-Null;$large=New-LogoPng 512;[IO.File]::WriteAllBytes((Join-Path $OutputDirectory 'logo.png'),$large)
$sizes=@(16,20,24,32,40,48,64,128,256);$images=@($sizes|ForEach-Object{New-LogoPng $_});$stream=[IO.File]::Create((Join-Path $OutputDirectory 'app.ico'));$w=[IO.BinaryWriter]::new($stream);$w.Write([uint16]0);$w.Write([uint16]1);$w.Write([uint16]$sizes.Count);$offset=6+16*$sizes.Count
for($i=0;$i-lt$sizes.Count;$i++){$d=if($sizes[$i]-eq 256){0}else{$sizes[$i]};$w.Write([byte]$d);$w.Write([byte]$d);$w.Write([byte]0);$w.Write([byte]0);$w.Write([uint16]1);$w.Write([uint16]32);$w.Write([uint32]$images[$i].Length);$w.Write([uint32]$offset);$offset+=$images[$i].Length};foreach($image in $images){$w.Write($image)};$w.Dispose();$stream.Dispose();Write-Host 'Generated app.ico and logo.png'
